Q1 Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Purpose of NumPy in Scientific Computing and Data Analysis

**NumPy** (Numerical Python) is a fundamental library for numerical and scientific computing in Python. It provides support for handling large, multi-dimensional arrays and matrices, along with a vast collection of high-level mathematical functions to operate on these arrays.

### Key Purposes of NumPy:
1. **Efficient Data Structures**: NumPy arrays (`ndarray`) are more efficient for handling large datasets compared to Python's built-in lists. They provide a compact, memory-efficient structure for representing large numerical data.
2. **Mathematical Operations**: It supports a wide range of mathematical operations like linear algebra, Fourier transforms, and random number generation, which are essential in scientific computing.
3. **Integration with Other Libraries**: NumPy is often used as a foundation for other scientific libraries like Pandas, SciPy, and Matplotlib, facilitating a seamless workflow for data analysis, scientific computing, and machine learning.

---

### Advantages of NumPy:
1. **Speed and Efficiency**:
   - **Vectorized Operations**: NumPy performs element-wise operations on arrays using highly optimized C and Fortran code, which is much faster than using Python loops.
   - **Memory Efficiency**: Arrays are stored more compactly than Python lists, saving memory and reducing computational overhead.
   
2. **Broadcasting**:
   - NumPy allows operations between arrays of different shapes and sizes through broadcasting. This eliminates the need to write explicit loops for operations like scalar multiplication and matrix addition.

3. **Multi-Dimensional Arrays**:
   - NumPy arrays can have more than one dimension (e.g., 2D for matrices, 3D for tensors). This makes NumPy ideal for handling complex datasets and conducting operations like matrix multiplication and image processing.

4. **Mathematical Functions and Aggregations**:
   - NumPy includes numerous built-in functions to perform tasks like:
     - **Element-wise operations**: addition, subtraction, multiplication.
     - **Statistical operations**: mean, median, standard deviation.
     - **Linear algebra**: matrix inversion, eigenvalues, and singular value decomposition (SVD).

5. **Interoperability with Other Libraries**:
   - NumPy is the foundation for many Python scientific computing libraries such as:
     - **Pandas** (for data manipulation).
     - **SciPy** (for scientific computations).
     - **Matplotlib** (for visualization).
     - **TensorFlow** and **PyTorch** (for deep learning).

6. **Handling Missing Data**:
   - Although primarily a feature of libraries like Pandas, NumPy provides tools to handle missing or invalid data points using special values like `NaN` (Not a Number), which is useful for numerical computations.

---

### Enhancing Python's Capabilities for Numerical Operations:
1. **Array Operations vs. Python Lists**:
   - Python lists are not ideal for numerical operations since they don’t support element-wise operations directly. NumPy enhances Python by providing a way to perform such operations efficiently.

2. **Multidimensional Arrays and Slicing**:
   - While Python lists are one-dimensional, NumPy arrays can be multi-dimensional (e.g., matrices, tensors), and slicing operations on these arrays are far more powerful and intuitive than on nested lists.

3. **Custom Data Types**:
   - NumPy supports custom data types and allows arrays of different data types (integers, floats, booleans), providing flexibility and precision when working with complex datasets.
   
4. **Interfacing with C/C++**:
   - NumPy enables the use of C/C++ and Fortran code, which allows for faster computations. This makes it a preferred library for performance-critical applications.

In summary, NumPy enhances Python’s capabilities for numerical and scientific computing by providing efficient, fast, and versatile tools for handling and performing operations on large datasets, making it invaluable in data analysis and computational tasks.

Q2 Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

In NumPy, both np.mean() and np.average() are used to compute the central tendency of an array of values, but they differ in their functionality and use cases. Here's a comparison:

1. np.mean():
Purpose:
Calculates the arithmetic mean (average) of the elements in an array along a specified axis.

Syntax: np.mean(a, axis=None, dtype=None, out=None, keepdims=False)

Key Features:
Computes the unweighted mean by default.

The axis can be specified to compute the mean along a particular dimension (for multi-dimensional arrays).

The data type (dtype) can be specified to control precision.

No support for weights.

In [ ]:
#Example
import numpy as np
a = np.array([1, 2, 3, 4, 5])
np.mean(a)
# Output: 3.0


3.0

np.average():

Purpose:

Computes the weighted average of an array, where each element can contribute differently to the final result based on a given set of weights.

Syntax:
np.average(a, axis=None, weights=None, returned=False)

Key Features:

By default, it behaves like np.mean() if no weights are provided.

Weights: You can provide a weights parameter to assign different importance to different elements.

If returned=True, it also returns the sum of weights, along with the average.

Can calculate along a specified axis for multi-dimensional arrays

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
np.average(a, weights=weights)
# Output: 3.6666666666666665


3.6666666666666665


When to Use One Over the Other:
Use np.mean() when:

You just need a simple arithmetic mean.
You are working with data where every value contributes equally to the final average.
Example: Calculating the average of a dataset of test scores, where all tests are equally important.
Use np.average() when:

You need to compute a weighted average, i.e., when certain elements have more importance or influence on the final result.
Example: Calculating a grade where different assignments/tests have different weights (e.g., homework = 10%, exams = 40%).

Q3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Ans Reversing a 1D Array

Method 1: Slicing ([::-1])
The easiest and most common way to reverse a 1D array in NumPy is by using slicing with [::-1].



In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)  # Output: [5 4 3 2 1]


[5 4 3 2 1]


Method 2: Using np.flip()

np.flip() reverses the order of elements along the specified axis. For a 1D array, there is only one axis (axis=0).

In [2]:
reversed_arr = np.flip(arr)
print(reversed_arr)  # Output: [5 4 3 2 1]


[5 4 3 2 1]


2. Reversing a 2D Array

For a 2D array,  can be reversed along different axes—rows (axis=0), columns (axis=1), or both.

Method 1: Slicing with [::-1]

Slicing can be used for both axes. For example, [::-1, :] reverses along the first axis (rows), and [:, ::-1] reverses along the second axis (columns).

In [3]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]


[[7 8 9]
 [4 5 6]
 [1 2 3]]


Method 2: Using np.flip()

np.flip() can reverse the array along a specific axis or along multiple axes at once.



In [4]:
flipped_both = np.flip(arr_2d, axis=(0, 1))
print(flipped_both)
# Output:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]


[[9 8 7]
 [6 5 4]
 [3 2 1]]


Method 3: Using np.fliplr() and np.flipud()

np.fliplr(): Reverses a 2D array left-to-right (flips along columns).

np.flipud(): Reverses a 2D array up-to-down (flips along rows).



In [5]:
flipped_lr = np.fliplr(arr_2d)
print(flipped_lr)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]


[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [6]:
flipped_ud = np.flipud(arr_2d)
print(flipped_ud)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]


[[7 8 9]
 [4 5 6]
 [1 2 3]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.


Ans. The data type of elements in NumPy array can be determined using the dtype attribute.

In [ ]:
# Example
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4])

# Determine the data type of elements
print(arr.dtype)


int64


Importance of Data Types in Memory Management and Performance

Memory Management:

NumPy arrays are more efficient than Python lists because they are densely packed in memory. The dtype determines how much space is allocated for each element. For instance, an int32 array allocates 4 bytes per integer, while an int64 array allocates 8 bytes. Choosing the correct data type helps optimize memory usage.

Smaller Data Types Save Memory: Using a smaller data type (e.g., int8, float32) can significantly reduce memory consumption, especially for large datasets. For example, an array with millions of elements will consume less memory if the elements are stored as int8 instead of int64.


Performance:
The data type also affects performance. Operations on smaller data types (like int8 or float32) can be faster than operations on larger data types (like int64 or float64) because less memory is transferred and cached by the processor.

Faster Computations: Using the appropriate data type can speed up calculations since smaller data types require fewer CPU cycles.

Vectorization: NumPy leverages vectorized operations, which means operations are applied element-wise on arrays, leading to faster execution. Efficient use of data types helps maximize this performance.
Choosing the right data type balances memory efficiency and computational speed, making it crucial for optimizing large-scale data processing tasks.

 Q5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

 Ans A NumPy ndarray (N-dimensional array) is a powerful, homogeneous data structure used for numerical computations. It is a grid of values, all of the same data type, indexed by a tuple of non-negative integers. Unlike Python lists, which are one-dimensional, ndarrays can have multiple dimensions, such as 1D, 2D (matrices), or higher.

Key Features of ndarray:

Homogeneous Data Type:
Every element in an ndarray must be of the same data type (e.g., all integers, all floats). This is in contrast to Python lists, which can hold mixed data types.

Multidimensional:
ndarrays support multiple dimensions. You can create arrays of any dimension, such as 1D vectors, 2D matrices, and higher-dimensional arrays (3D, 4D, etc.). The dimensions are defined by the array's shape, which is a tuple indicating the size along each dimension.

Efficient Memory Usage:
NumPy arrays are densely packed in memory, unlike Python lists, which are arrays of pointers to objects. This compact memory layout allows for faster access and manipulation of data.

Vectorized Operations:
ndarrays allow element-wise operations and broadcasting, where operations are applied simultaneously across all elements without the need for explicit loops. This makes computations much faster than using Python loops.

Fixed Size:
Once created, the size (shape) of an ndarray is fixed. To modify its size, you must create a new array or reshape the existing one, unlike Python lists, which can dynamically resize.

Advanced Indexing and Slicing:
NumPy supports complex slicing and indexing, allowing efficient extraction and modification of subarrays. You can use slicing, Boolean indexing, and even fancy indexing to work with data.

In [ ]:
#Example
import numpy as np

# Creating a 1D ndarray
arr = np.array([1, 2, 3])

# Creating a 2D ndarray
arr_2d = np.array([[1, 2], [3, 4]])


Differences

Data Type:

ndarrays are homogeneous (all elements must be of the same data type).

Python lists are heterogeneous (can hold elements of different data types).

Memory Efficiency:

ndarrays use a compact, contiguous memory layout, making them more memory-efficient.

Python lists are arrays of pointers, resulting in higher memory consumption.

Performance:

ndarrays support vectorized operations for faster computations.

Python lists require explicit loops, making them slower for numerical operations.

Size Flexibility:

ndarrays have a fixed size once created.

Python lists can dynamically grow or shrink in size.

Dimensionality:

ndarrays support multiple dimensions (1D, 2D, 3D, etc.) natively.

Python lists are typically 1D, with nested lists needed for higher dimensions.

Mathematical Operations:

ndarrays allow element-wise operations without loops.

Python lists require loops for arithmetic operations on elements.

Indexing and Slicing:

ndarrays support advanced slicing, indexing, and broadcasting across multiple dimensions.

Python lists offer basic slicing and lack advanced indexing features.

Q6  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans Performance Benefits of NumPy Arrays Over Python Lists for Large-Scale Numerical Operations:
Memory Efficiency:

NumPy Arrays: NumPy arrays (ndarrays) are stored in contiguous blocks of memory, and all elements are of the same data type. This means that NumPy arrays are much more compact and memory-efficient than Python lists. For large datasets, this reduced memory footprint allows for faster access to data and lower memory usage.

Python Lists: In contrast, Python lists are arrays of pointers to objects, and each element can be of a different data type. This results in significant memory overhead, especially when handling large datasets.

Vectorized Operations:

NumPy Arrays: NumPy supports vectorized operations, which allow element-wise computations to be executed without using explicit loops. Operations such as addition, multiplication, and other arithmetic tasks are applied to the entire array at once, utilizing optimized C and Fortran libraries under the hood.

Python Lists: Python lists do not support vectorized operations, so mathematical operations require explicit loops, resulting in higher execution times and lower efficiency for large-scale data.

Low-Level Optimizations:

NumPy Arrays: NumPy is written in C and heavily optimized for performance. When performing operations on arrays, NumPy directly accesses the underlying C libraries, bypassing Python’s dynamic typing system and interpreter overhead. This leads to a significant speed boost when working with large datasets.


Python Lists: Python lists are built on dynamic typing, where each operation involves checking the data type and handling references. This overhead becomes a performance bottleneck when dealing with large datasets.

Broadcasting:

NumPy Arrays: NumPy supports broadcasting, which allows arrays of different shapes to interact in arithmetic operations without needing to reshape them explicitly. Broadcasting minimizes the need for loops and improves computational efficiency, making it easier and faster to work with large datasets.

Python Lists: Python lists do not have a broadcasting feature, requiring manual iteration and handling of different shapes, which slows down operations for large-scale data.

Efficient Element-wise Operations:

NumPy Arrays: Operations like addition, multiplication, and division between arrays or between an array and a scalar are handled element-wise efficiently in NumPy. These operations are performed in compiled code, leveraging the CPU’s vectorized instructions.

Python Lists: Performing element-wise operations in Python lists involves explicit loops, which introduces Python's interpreter overhead. This significantly increases the time complexity, especially for large datasets.

Handling Multi-dimensional Data:

NumPy Arrays: NumPy arrays are natively designed to handle multi-dimensional data. Operations on 2D, 3D, or higher-dimensional arrays are optimized and performed efficiently, making NumPy a go-to tool for numerical computing and machine learning tasks.

Python Lists: Handling multi-dimensional data in Python lists requires nested lists and explicit loops, which can make the code complex, slower, and less readable.

Parallelism and Optimization:

NumPy Arrays: Many of NumPy’s operations are parallelized internally, leveraging multi-core CPUs for performance optimization. This provides an additional boost when working with large datasets and performing repetitive operations.

Python Lists: Python lists do not natively support parallelism or multi-threaded operations, leading to slower execution times for computationally intensive tasks.

Conclusion:
For large-scale numerical operations, NumPy arrays offer substantial performance benefits over Python lists. They are more memory-efficient, leverage vectorized operations, and take advantage of low-level optimizations. Python lists, while more flexible for general-purpose use, are not optimized for numerical computations, making NumPy the preferred tool for tasks involving large datasets and intensive calculations.

Q7  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Ans 7 In NumPy, the vstack() and hstack() functions are used to stack arrays along different axes, but they work differently depending on the stacking direction.

1. vstack() – Vertical Stacking:
Functionality: The vstack() function stacks arrays vertically, row-wise. It concatenates arrays along the vertical axis (i.e., axis 0). The arrays being stacked must have the same number of columns.

2. hstack() – Horizontal Stacking:
Functionality: The hstack() function stacks arrays horizontally, column-wise. It concatenates arrays along the horizontal axis (i.e., axis 1). The arrays being stacked must have the same number of rows.

Key Differences Between vstack() and hstack():

Direction:

vstack() stacks arrays vertically (row-wise) along axis 0.

hstack() stacks arrays horizontally (column-wise) along axis 1.

Dimensionality Requirements:

For vstack(), arrays must have the same number of columns (i.e., the same second dimension in 2D arrays).

For hstack(), arrays must have the same number of rows (i.e., the same first dimension in 2D arrays).


In [ ]:
# Example
import numpy as np

# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertically stacking the arrays
result = np.vstack((arr1, arr2))
print(result)


[[1 2 3]
 [4 5 6]]


In [ ]:
# Example 2
# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Horizontally stacking the arrays
result = np.hstack((arr1, arr2))
print(result)


[1 2 3 4 5 6]


Q8 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.


Ans8 The fliplr() and flipud() functions in NumPy are used to reverse or flip arrays, but they operate along different axes. Here’s a breakdown of their differences and effects on arrays.

1. fliplr() – Flip Left to Right (Horizontally):

Functionality:

The fliplr() function flips an array horizontally, i.e., it reverses the order of columns. It applies to 2D arrays (or higher) and works along the last axis (axis 1).

Effect on Arrays:

For 1D arrays: It does not apply (raises an error) because there is no second dimension (axis 1).

For 2D arrays: It flips the array from left to right by reversing the order of columns.

For 3D arrays: fliplr() will reverse the order of the elements along the last axis, which in 3D is the second dimension (the columns).

2. flipud() – Flip Up to Down (Vertically):

Functionality:

The flipud() function flips an array vertically, i.e., it reverses the order of rows. It applies to 2D arrays (or higher) and works along the first axis (axis 0).

Effect on Arrays:

For 1D arrays: It applies and simply reverses the elements since a 1D array has only one axis.

For 2D arrays: It flips the array from top to bottom by reversing the order of rows.

For 3D arrays: flipud() flips the array along the first axis, i.e., it swaps the rows of the first axis.

Key Differences Between fliplr() and flipud():

Axis of Operation:

fliplr(): Flips arrays horizontally (left to right) along axis 1 (columns).

flipud(): Flips arrays vertically (up to down) along axis 0 (rows).

Dimensional Applicability:

fliplr() only works for arrays with at least 2 dimensions (because it operates on columns).

flipud() can work for both 1D arrays (reversing their elements) and higher-dimensional arrays (flipping rows).

Effect on 2D Arrays:

fliplr(): Reverses the order of columns in each row.

flipud(): Reverses the order of rows.

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is similar to the split() function, but with the added flexibility of handling uneven splits, making it particularly useful when the array cannot be evenly divided by the specified number of splits.

Functionality of array_split():
Purpose: array_split() divides an array into a specified number of sub-arrays. Unlike split(), which raises an error if the array cannot be split evenly, array_split() allows for uneven splitting, distributing the remaining elements across the sub-arrays.

Handling of Uneven Splits:
If the array cannot be split evenly into the specified number of sub-arrays, array_split() ensures that the resulting sub-arrays are as equal in size as possible. The larger sub-arrays are placed earlier in the output. This means that the first few sub-arrays may have one more element than the later sub-arrays.

Key Differences from split():
split() requires that the array can be divided exactly by the number of splits; otherwise, it raises an error.

array_split() can handle uneven splits, ensuring that sub-arrays are as evenly distributed as possible.

Effect on Multi-dimensional Arrays:
array_split() can also work on multi-dimensional arrays. The axis argument determines along which dimension the array will be split.

Q 10 Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array


Ans 1 Vectorization:

Definition: Vectorization refers to the process of applying operations (such as arithmetic, comparisons, etc.) on entire arrays (or vectors) in a single step, without the need for explicit loops. This allows NumPy to execute operations at a much faster pace by internally utilizing optimized C and Fortran routines.

Reasons for Efficiency:

By avoiding explicit Python loops, vectorization reduces the overhead associated with the Python interpreter. Instead, the operation is performed at the compiled C level, which is far more efficient.
It enables parallelism, meaning the CPU can perform multiple computations simultaneously, leading to significant performance improvements.

2. Broadcasting:
Definition: Broadcasting is a mechanism that allows NumPy to perform element-wise operations on arrays with different shapes, by automatically expanding the smaller array to match the shape of the larger one. This eliminates the need for reshaping or duplicating arrays, thus saving memory and improving performance.

Working: When arrays of different shapes are involved in an operation, NumPy applies the following broadcasting rules:

The dimensions of the arrays are compared from right to left.
If the dimensions are the same, or one of the arrays has size 1 in that dimension, they are compatible, and broadcasting is possible.
The smaller array is “stretched” or replicated across the larger array so that they can be combined element-wise.

Elimination of Explicit Loops:

Both vectorization and broadcasting allow you to operate on entire arrays without writing loops. This not only simplifies the code but also eliminates the inefficiency of Python loops, which can be slow for large datasets.


Lower-Level Optimizations:

Vectorized operations are implemented using low-level C or Fortran routines, bypassing Python’s overhead. These operations are highly optimized for performance, enabling faster computations on large arrays.

Parallel Processing:

Modern CPUs have multiple cores and can perform parallel computations. Vectorized operations allow NumPy to take advantage of these optimizations, performing many calculations simultaneously.

Memory Efficiency:

Broadcasting avoids unnecessary memory consumption by not creating copies of arrays. Instead of physically expanding arrays to match shapes, NumPy adjusts the shape dynamically during computation, saving both time and memory.

Conciseness and Readability:

Vectorized and broadcasted operations are typically written in a single line, making the code more concise, readable, and easier to debug. This is especially useful for numerical and scientific computations.

In [ ]:
# Practical Questions
#Q1  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

import numpy as np

array = np.random.randint(1, 101, size=(3, 3))

print("Original Array:")
print(array)

# Interchange rows and columns using transpose
interchanged_array = array.transpose()

print("\nArray with Rows and Columns Interchanged (Transposed):")
print(interchanged_array)


Original Array:
[[73  9 15]
 [55 93 94]
 [19 26 60]]

Array with Rows and Columns Interchanged (Transposed):
[[73 55 19]
 [ 9 93 26]
 [15 94 60]]


In [ ]:
# Q2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

# Generate a 1D array with 10 elements
arr_1d = np.arange(10)

arr_2x5 = arr_1d.reshape(2, 5)
print("2x5 array:\n", arr_2x5)

# Reshape it into a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)
print("\n5x2 array:\n", arr_5x2)


2x5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# Q3 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Create a 4x4 array with random float values
array = np.random.rand(4, 4)

# Create a 6x6 array filled with zeros
bordered_array = np.zeros((6, 6))

# Insert the original array into the center of the bordered array
bordered_array[1:5, 1:5] = array

print("Original Array:\n", array)
print("\nArray with Zero Border:\n", bordered_array)


Original Array:
 [[0.3649933  0.41700425 0.45967589 0.20793555]
 [0.58885324 0.71631338 0.05928552 0.13295289]
 [0.44845547 0.78081407 0.97296913 0.80018329]
 [0.69064058 0.86651381 0.49204098 0.77791748]]

Array with Zero Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.3649933  0.41700425 0.45967589 0.20793555 0.        ]
 [0.         0.58885324 0.71631338 0.05928552 0.13295289 0.        ]
 [0.         0.44845547 0.78081407 0.97296913 0.80018329 0.        ]
 [0.         0.69064058 0.86651381 0.49204098 0.77791748 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
# Q4 Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

array = np.arange(10, 61, 5)
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


In [ ]:
# Q5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

strings = np.array(['python', 'numpy', 'pandas'])

# Uppercase
uppercase_strings = np.char.upper(strings)
print("Uppercase:", uppercase_strings)

# Lowercase
lowercase_strings = np.char.lower(strings)
print("Lowercase:", lowercase_strings)

# Title case
titlecase_strings = np.char.title(strings)
print("Titlecase:", titlecase_strings)

# Swapcase
swapcase_strings = np.char.swapcase(strings)
print("Swapcase:", swapcase_strings)


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Titlecase: ['Python' 'Numpy' 'Pandas']
Swapcase: ['PYTHON' 'NUMPY' 'PANDAS']


In [ ]:
# Q6 Generate a NumPy array of words. Insert a space between each character of every word in the array

import numpy as np

words = np.array(['hello', 'world', 'numpy'])

# Insert a space between each character using a list comprehension and join
spaced_words = np.array([' '.join(list(word)) for word in words])

print(spaced_words)


['h e l l o' 'w o r l d' 'n u m p y']


In [ ]:
# Q7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
addition_result = array1 + array2
print("Element-wise Addition:\n", addition_result)

# Element-wise subtraction
subtraction_result = array1 - array2
print("\nElement-wise Subtraction:\n", subtraction_result)

# Element-wise multiplication
multiplication_result = array1 * array2
print("\nElement-wise Multiplication:\n", multiplication_result)

# Element-wise division
division_result = array1 / array2
print("\nElement-wise Division:\n", division_result)


Element-wise Addition:
 [[ 6  8]
 [10 12]]

Element-wise Subtraction:
 [[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]

Element-wise Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
#  Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


In [ ]:
# Q9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

import numpy as np

def is_prime(n):
  """Checks if a number is prime."""
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]
print("Prime numbers in the array:", prime_numbers)


Prime numbers in the array: [769, 109, 883, 353, 577, 461, 593, 733, 601, 797, 307, 13, 937, 227, 127, 619]


In [ ]:
#  Q 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 35, size=30)  # Example temperatures between 15 and 35 degrees Celsius

# Calculate weekly averages
weekly_averages = []
for i in range(0, len(daily_temperatures), 7):
  week_temps = daily_temperatures[i:i+7]
  if len(week_temps) > 0:
    weekly_average = np.mean(week_temps)
    weekly_averages.append(weekly_average)

# Display the weekly averages
print("Daily Temperatures:", daily_temperatures)
print("\nWeekly Averages:", weekly_averages)


Daily Temperatures: [29 23 19 24 24 17 30 27 24 18 22 33 34 20 27 26 30 32 23 23 28 34 26 30
 33 16 21 27 23 29]

Weekly Averages: [23.714285714285715, 25.428571428571427, 27.0, 26.714285714285715, 26.0]
